url: 'https://nathanalderson.github.io'
baseurl: ''
title: 'Nathan Alderson'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json

include:
  - keybase.txt
  - .nojekyll